GET http://localhost:8000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsInVzZXJuYW1lIjoibWFobXVscCIsImVtYWlsIjoibWFobXVscHJhdGFtYTFAZ21haWwuY29tIiwiaWF0IjoxNzAyMjU0NDYwLCJleHAiOjE3MDIyNTQ1MDV9.FT2cfq1Q7sW0xbgV8RdqbO2WYiQA7puq16pnzFGbDak

###

POST http://localhost:8000/register
Content-Type: application/json

{
    "username": "mahmulp",
    "email": "mahmulpratama1@gmail.com",
    "password": "test",
    "phone": "081361626766"
}

###

POST http://localhost:8000/login
Content-Type: application/json

{
    "email": "mahmulpratama1@gmail.com",
    "password": "test"
}

###

GET http://localhost:8000/token

###

DELETE http://localhost:8000/logout

###

GET http://localhost:8000/vouchers

###
GET http://localhost:8000/contacts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsInVzZXJuYW1lIjoibWFobXVscCIsImVtYWlsIjoibWFobXVscHJhdGFtYTFAZ21haWwuY29tIiwiaWF0IjoxNzAyMjU0NDYwLCJleHAiOjE3MDIyNTQ1MDV9.FT2cfq1Q7sW0xbgV8RdqbO2WYiQA7puq16pnzFGbDak

###

POST http://localhost:8000/post-message
Content-Type: application/json

{
    "email": "mahmulpratama1@gmail.com",
    "name": "Machmul Pratama",
    "phone": "08527159",
    "subject": "Teruntuk Kamu hidup dan matiku",
    "message": "Kutuliskan kenagnan tentang caraku menemukan dirimu asik asik jos"
}